volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
services:
  react:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./frontend/fast-fit-frontend:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: fastfit@example.com
      PGADMIN_DEFAULT_PASSWORD: fastfit
      PGADMIN_DISABLE_POSTFIX: 1

  postgres:
    image: postgres:14.2-bullseye
    volumes:
          # for your initialization scripts
      - ./data/postgres/init:/docker-entrypoint-initdb.d
          # for the data stored by PostgreSQL
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_MULTIPLE DATABASES: accounts
      POSTGRES_PASSWORD: fastfit
    ports:
      - 15432:5432

  accounts:
    build:
      context: ./backend/accounts/api
      dockerfile: ./Dockerfile.dev
    ports:
      - "8010:8000"
    volumes:
      - ./backend/accounts/api:/app
    depends_on:
      - postgres
    environment:
      SECRET_KEY: db0a49ab25db171089e1a3950f31f3288df643c7c33ede3f38d6bf7788569e24
      PGHOST: postgres
      DATABASE_URL: postgresql://fastfit:fastfit@postgres:5432/accounts
      PGDATABASE: accounts
      PGUSER: fastfit
      PGPASSWORD: fastfit
    # finish accounts 

